title: Yongsang Shin
description: SKKU Computer Science
site_title: 'Yongsang Shin'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: ydykim
blog_url: https://www.nagekar.com
email: ydykim@naver.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 