title: Yongsang Shin
description: SKKU Computer Science
site_title: 'Yongsang Shin'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: ydykim
email: sys631847@gmail.com

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 